# Generated by Django 3.1.7 on 2021-04-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20210419_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
