# Generated by Django 3.2 on 2021-05-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('questions', '0009_auto_20210529_1248'),
        ('answers', '0004_response_finalized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['response', 'question'], 'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Questionário respondido', 'verbose_name_plural': 'Questionários respondidos'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='resposta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de criação'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='data de modificação'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='pergunta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answers.response', verbose_name='questionário'),
        ),
        migrations.AlterField(
            model_name='response',
            name='finalized',
            field=models.BooleanField(default=False, verbose_name='finalizado'),
        ),
        migrations.AlterField(
            model_name='response',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session', verbose_name='sessão'),
        ),
    ]
