# Generated by Django 3.2 on 2021-05-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_auto_20210529_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='interview_uuid',
        ),
    ]
