# Generated by Django 3.2 on 2021-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='category',
            name='text_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_3',
            field=models.TextField(blank=True),
        ),
    ]
