# Generated by Django 3.2 on 2021-05-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text_1',
            field=models.TextField(blank=True, verbose_name='Média >= 5'),
        ),
        migrations.AlterField(
            model_name='category',
            name='text_2',
            field=models.TextField(blank=True, verbose_name='2.5 < Média > 5'),
        ),
        migrations.AlterField(
            model_name='category',
            name='text_3',
            field=models.TextField(blank=True, verbose_name='Média <= 25'),
        ),
    ]
