# Generated by Django 3.2 on 2021-05-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20210521_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['order'], 'verbose_name': 'Grupo de perguntas', 'verbose_name_plural': 'Grupos de perguntas'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='atalho'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.group', verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, verbose_name='opções'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=255, verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, verbose_name='obrigatória'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('RADIO', 'radio'), ('SELECT', 'select'), ('CHECKBOX', 'dropbox'), ('TEXT', 'text'), ('RANK', 'rank'), ('RANK_2', 'rank_2')], default='RANK', max_length=30, verbose_name='tipo'),
        ),
    ]
